# Generated by Django 5.2.13 on 2026-06-01 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_pharmacyinventory_pathologyreport_prescription_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatentInvention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=200)),
                ('clinic_name', models.CharField(max_length=200)),
                ('clinic_address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('inventor_names', models.TextField(help_text='Comma-separated list of inventor names')),
                ('inventor_designations', models.TextField(blank=True, help_text='Comma-separated designations')),
                ('inventor_contact', models.TextField(blank=True, help_text='Comma-separated contact numbers')),
                ('title', models.CharField(max_length=300)),
                ('innovation_type', models.CharField(choices=[('dental_instrument', 'Dental Instrument'), ('dental_equipment', 'Dental Equipment'), ('dental_software', 'Dental Software'), ('dental_material', 'Dental Material'), ('treatment_method', 'Treatment Method'), ('diagnostic_tool', 'Diagnostic Tool'), ('ai_solution', 'AI-Based Solution'), ('other', 'Other')], max_length=30)),
                ('problem_statement', models.TextField(help_text='Describe the problem or limitation in current dental practice')),
                ('detailed_description', models.TextField(help_text='Provide a complete explanation of the invention')),
                ('novel_features', models.TextField(help_text='What makes the invention new and unique?')),
                ('advantages', models.TextField(help_text='List the benefits compared to existing solutions')),
                ('technical_drawings', models.FileField(blank=True, null=True, upload_to='patent_drawings/')),
                ('technical_specifications', models.FileField(blank=True, null=True, upload_to='patent_specs/')),
                ('prior_art_search_done', models.BooleanField(default=False)),
                ('prior_art_details', models.TextField(blank=True)),
                ('public_disclosure', models.BooleanField(default=False)),
                ('public_disclosure_details', models.TextField(blank=True)),
                ('expected_applications', models.TextField(help_text='Expected applications and use cases')),
                ('target_market', models.CharField(max_length=500)),
                ('estimated_commercial_value', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('filed', 'Filed with Patent Office'), ('granted', 'Patent Granted')], default='draft', max_length=20)),
                ('patentability_assessment', models.CharField(blank=True, choices=[('novel', 'Novel'), ('inventive_step', 'Inventive Step Present'), ('industrial_applicable', 'Industrially Applicable'), ('requires_review', 'Requires Further Review')], max_length=30)),
                ('reviewer_name', models.CharField(blank=True, max_length=200)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patent_inventions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
